# Generated by Django 2.2.4 on 2019-09-04 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0003_auto_20190905_0056'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='imgPredict',
        ),
        migrations.AddField(
            model_name='record',
            name='imgPredict_res',
            field=models.CharField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='imgPredict_sqz',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
