# Generated by Django 2.2.4 on 2019-09-07 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0004_auto_20190905_0105'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cookie',
        ),
        migrations.AlterField(
            model_name='record',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
